### ISSUE TITLE
магазины

### ISSUE THREAD

**Issue by Strranger08** [SomeOneUnknown/SATGv2#3]
магазыны с рандомными вещами

**Comment by Strranger08** [comment]
ну чтоб прицел еще и найти надо было

**Comment by Enclave2020** [comment]
@Strranger08 Как ты себе это представляешь?)0

**Comment by Strranger08** [comment]
чтоб был не сразу весь асортимент а только рандомная 1/4
и менялась каждые пол часа

**Comment by Strranger08** [comment]
и вообще все магазины можно в один совместить

**Comment by Enclave2020** [comment]
@Strranger08 В зависимости от рарности вещи или просто рандом?

**Comment by Strranger08** [comment]
рандом

**Comment by Enclave2020** [comment]
@Strranger08 Тогда вероятность продажи GM6 будет равна вектору)0

**Comment by Strranger08** [comment]
если денег на нее хватит

**Comment by Enclave2020** [comment]
@Strranger08 
![arma3 2016-11-28 00-37-50-23](https://cloud.githubusercontent.com/assets/12204579/20652661/f56b010a-b505-11e6-9c27-efab2a048b57.png)
