### ISSUE TITLE
Фрэндли фаер есть

### ISSUE THREAD

**Issue by Enclave2020** [SomeOneUnknown/SATGv2#35]

**Comment by Strranger08** [comment]
оставь френдли фаер но добавь штраф 1000$

**Comment by Enclave2020** [comment]
@Strranger08 И деньги в минус, живешь в кредит

**Comment by Enclave2020** [comment]
FAR_Revive удаляет при старте и респавне все побочные хэндлеры на получение урона
Нужно либо изменять его код, либо забить)0

**Comment by Enclave2020** [comment]
Можно реализовать через hit хэндлер

**Comment by Enclave2020** [comment]
Сделал но временно отключил
