### ISSUE TITLE
мало разнообразности врагов

### ISSUE THREAD

**Issue by Strranger08** [SomeOneUnknown/SATGv2#4]
сделай патрули, конвои и тд

**Comment by Enclave2020** [comment]
@Strranger08 Патрули и так есть, враги не стоят на месте. А конвои какие?

**Comment by Strranger08** [comment]
чтоб по дорогам когда едеш иногда спавнились враги

**Comment by Strranger08** [comment]
и враги сечас очень тупые
я зашел в город а там кучка наспавнилась на глазах в одном месте

**Comment by Enclave2020** [comment]
@Strranger08 Повысить им скилл чтоб лютыми были?)0

**Comment by Antoxer** [comment]
NE NADO

**Comment by Enclave2020** [comment]
В системе случайных событий будет
