### ISSUE TITLE
нужены лагеря 

### ISSUE THREAD

**Issue by Strranger08** [SomeOneUnknown/SATGv2#5]
тип построил лагерь и в нем спавн. и чтоб на карте можно было выбрать на какой лагерь спавнится

**Comment by Enclave2020** [comment]
@Strranger08 И палатку нужно покупать, не?

**Comment by Strranger08** [comment]
да

**Comment by Strranger08** [comment]
можно еще разделить на класы маленькая средняя большая
в маленькой только спавн 
в средней 1 рандомный торговец 
в большой 2 торговца

**Comment by Enclave2020** [comment]
@Strranger08 Торговцы в палатках слишком люто)0

**Comment by Enclave2020** [comment]
@Strranger08 
Можно сделать респавны на местах захваченных городов, используя при этом дефолтную фичу выбора респавн поинтов армы, сойдет?)0

![image](https://cloud.githubusercontent.com/assets/12204579/20653291/13f759e4-b514-11e6-9873-8144734d0301.png)

**Comment by Enclave2020** [comment]
Или же добавлю в продажу IR гранаты, которые при выкидывании создают спавнпоинт

**Comment by Enclave2020** [comment]
В магазине покупаешь IR гранату, кидаешь - спавн поинт появляется
