### ISSUE TITLE
Добавить дефолтный перк на крафт костра

### ISSUE THREAD

**Issue by Felk1n** [SomeOneUnknown/SATGv2#51]
кд костра 30мин или больше.

**Comment by Enclave2020** [comment]
@Felk1n Раз в полчаса?
Мб покупать в магазине дрова?)0

**Comment by Felk1n** [comment]
@SomeOneUnknown можно, но вряд ли кто-то будет ради этого что-то покупать, ибо мы редко так гуляем, но если вдруг, то можно перк юзать, а так никто не будет ещё дрова докупать.

**Comment by Enclave2020** [comment]
@Felk1n Shift + C, можно раз в полчаса
![arma3 2016-11-27 14-21-02-16](https://cloud.githubusercontent.com/assets/12204579/20648347/e1f18562-b4ac-11e6-9f55-a2fe071f1b99.png)
