### ISSUE TITLE
Убрать watermark слева вверху

### ISSUE THREAD

**Issue by Felk1n** [SomeOneUnknown/SATGv2#54]
Так-же можно шрифт температуры и далларов, поменьше  сделать.

**Comment by Enclave2020** [comment]
НО КАК ЖЕ САТГ ТРЕЙДМАРК?
А вообще то для скринов, мб поменьше сделаю

**Comment by Enclave2020** [comment]
@Felk1n Можно шрифт поменять еще, вопрос на какой
![arma3fonts](https://cloud.githubusercontent.com/assets/12204579/20647431/b839c0c8-b49c-11e6-97cc-86504a2d69b6.png)

**Comment by Enclave2020** [comment]
Уменьшенным как-то ужасно выглядит
![arma3 2016-11-27 13-13-02-80](https://cloud.githubusercontent.com/assets/12204579/20647974/54b2d0a6-b4a3-11e6-93e6-717986c3fab2.png)

**Comment by Enclave2020** [comment]
Уменьшил ватермарк, но оставил)0
Температуру и деньги не трогал
