### ISSUE TITLE
Рисовать иконку над ящиком сквозь стены

### ISSUE THREAD

**Issue by Enclave2020** [SomeOneUnknown/SATGv2#57]
Стоит или нет?
@Felk1n @SadSapDept @Strranger08
Вполне возможно негативное влияние на производительность

**Comment by Strranger08** [comment]
КАТЕГОРИЧЕСКИ НЕТ

**Comment by Enclave2020** [comment]
@Strranger08 Мы вчера минут 15 искали ящик в Бёрезино

**Comment by Strranger08** [comment]
сделай чтоб они на карте помечались
тип мелкий такой значок

**Comment by Enclave2020** [comment]
@Strranger08 Ну не знаю)0 По сути на карте - это центр кружка

**Comment by Felk1n** [comment]
Пока-что нарисуй, потом посмотрим если будет слишком изи, то уберем.

**Comment by Antoxer** [comment]
# **Da**

**Comment by Enclave2020** [comment]
Короче, это не целесообразно в плане производительности. Нужно искать ящики, или хранить отдельный массив с ними, при каждом кадре получать их позицию, проверять дистанцию игрока до ящика и выводить текст, нафиг)0
