### ISSUE TITLE
Зимний камуфляж технике и врагам

### ISSUE THREAD

**Issue by Enclave2020** [SomeOneUnknown/SATGv2#58]

**Comment by Antoxer** [comment]
**Vragam ne nado**

**Comment by Enclave2020** [comment]
@Antoxer Чому нет?)0

**Comment by Antoxer** [comment]
@SomeOneUnknown a za4em

**Comment by Enclave2020** [comment]
@Antoxer Ну у них БТРы, танки и прочее будет в лесном камуфляже)0

**Comment by Antoxer** [comment]
@SomeOneUnknown  da

**Comment by Enclave2020** [comment]
@Antoxer ЕТО НЕ НОРМА

**Comment by Enclave2020** [comment]
Стоковые камуфляжи армы не так бросаются в глаза. Плюс меньше вес миссии без этой фичи
