### ISSUE TITLE
добавить возможность обмена деньгами

### ISSUE THREAD

**Issue by Strranger08** [SomeOneUnknown/SATGv2#63]

**Comment by Enclave2020** [comment]
@Strranger08 ДЕРЖИ
![1440155736058](https://cloud.githubusercontent.com/assets/12204579/20650941/79c03542-b4e3-11e6-970f-42affcf27dd0.jpg)

**Comment by Enclave2020** [comment]
Смотришь на игрока, жмешь P и ему отдается 1000
