### ISSUE TITLE
Сделай иконку температуры рядом с иконкой еды

### ISSUE THREAD

**Issue by SadSapDept** [SomeOneUnknown/SATGv2#8]
Например:

1. отображение в процентах
2.  заполняющийся или убывающий сосуд,
![heat-icon](https://cloud.githubusercontent.com/assets/24190469/20640845/3b62b928-b3f3-11e6-9e89-b358f32a4aaa.png)
3.  банально цветовая гамма: от теплого до холодного оттенка цвета.

**Comment by Enclave2020** [comment]
В арме нельзя менять цвет иконки или же динамически рисовать на них, так что плавные переходы сделать не выйдет. Пока вернул как было, сбоку отображение градусов около градусника

**Comment by Enclave2020** [comment]
Хотя, можно просто сделать пару статусов

**Comment by Enclave2020** [comment]
Сделал пять картинок опустошения градусника, убрал отображение в градусах
