### ISSUE TITLE
Новое радио

### ISSUE THREAD

**Issue by Enclave2020** [SomeOneUnknown/SATGv2#93]
Старая музыка на радио уже приелась, предлагайте новые треки (видео с ютуба)
Голосуйте пальцами за предложения других - 4 голоса и добавляю в игру
За себя голосовать **нужно** тоже)0

**Comment by Enclave2020** [comment]
https://m.youtube.com/watch?v=MV_3Dpw-BRY

**Comment by Enclave2020** [comment]
https://m.youtube.com/watch?v=YnzgdBAKyJo

**Comment by Enclave2020** [comment]
https://m.youtube.com/watch?v=iX-QaNzd-0Y

**Comment by Strranger08** [comment]
https://www.youtube.com/watch?v=A572eclLc68

**Comment by Enclave2020** [comment]
https://m.youtube.com/watch?v=IkAp5gAYDUQ

**Comment by Enclave2020** [comment]
https://m.youtube.com/watch?v=iRpxzWRAoY4

**Comment by Enclave2020** [comment]
https://m.youtube.com/watch?v=hCEjfEIeUsg

**Comment by Felk1n** [comment]
https://www.youtube.com/watch?v=KuuMLI6h-vk жду этот шедевр у себя в машине!

**Comment by Felk1n** [comment]
https://www.youtube.com/watch?v=Si9nM9h4sRQ вот короткая версия .

**Comment by Strranger08** [comment]
https://www.youtube.com/watch?v=oLhBcG3OWRM

**Comment by Strranger08** [comment]
https://www.youtube.com/watch?v=GjsnYmi4z0U

**Comment by Felk1n** [comment]
https://www.youtube.com/watch?v=49YjKTOYeNI Если этого не будет в моем хаммере, то мне будет плохо.

**Comment by Strranger08** [comment]
https://www.youtube.com/watch?v=TmM_zzMBaAo

**Comment by Felk1n** [comment]
https://www.youtube.com/watch?v=IS3lghK9-tc ну без этого ни на одной войне.

**Comment by SomeOneUnknown** [comment]
@Strranger08 Клятэ анимэ

**Comment by Strranger08** [comment]
ставь + и листай дальше

**Comment by Strranger08** [comment]
https://www.youtube.com/watch?v=wjyNrGUD2SI

**Comment by Strranger08** [comment]
https://www.youtube.com/watch?v=HIdtVM2tZrw

**Comment by Felk1n** [comment]
https://www.youtube.com/watch?v=R__-odywmeg

**Comment by Strranger08** [comment]
https://www.youtube.com/watch?v=O8ZZQiKB4lw

**Comment by Strranger08** [comment]
https://www.youtube.com/watch?v=ZZey8n6NPc4

**Comment by Strranger08** [comment]
https://www.youtube.com/watch?v=A1Qb4zfurA8&list=RDRdJXZqY_v3o&index=2

**Comment by Strranger08** [comment]
https://youtu.be/rX3W5evpeJE

**Comment by SomeOneUnknown** [comment]
Вы чо, другу лоесы ставите?)0

**Comment by Strranger08** [comment]
https://www.youtube.com/watch?v=RVmG_d3HKBA

**Comment by Strranger08** [comment]
не просто все годное кидаем

**Comment by Enclave2020** [comment]
https://youtu.be/KckCsw_JyJI

**Comment by Enclave2020** [comment]
https://youtu.be/86khmc6y1yE

**Comment by Enclave2020** [comment]
https://youtu.be/5t99bpilCKw

**Comment by Enclave2020** [comment]
https://youtu.be/BJk6gZuPKRE

**Comment by Enclave2020** [comment]
https://youtu.be/eJlN9jdQFSc

**Comment by Enclave2020** [comment]
https://youtu.be/N3kkNfH4yco
)000

**Comment by Enclave2020** [comment]
https://youtu.be/6KKKGpAZHAA

**Comment by Enclave2020** [comment]
https://youtu.be/L-iepu3EtyE

**Comment by Enclave2020** [comment]
https://youtu.be/z3MH4l1-t_8

**Comment by Enclave2020** [comment]
https://youtu.be/okC4hw8IPYg

**Comment by Enclave2020** [comment]
https://youtu.be/JGCsyshUU-A

**Comment by Enclave2020** [comment]
https://youtu.be/QQdPiBvpCdE

**Comment by Enclave2020** [comment]
https://youtu.be/eOvExilXf9k

**Comment by Enclave2020** [comment]
https://youtu.be/-czc_k_yoQ8

**Comment by Enclave2020** [comment]
https://youtu.be/LnpaaCGg-k8

**Comment by Enclave2020** [comment]
https://youtu.be/NZs43m3_oZs

**Comment by Enclave2020** [comment]
https://youtu.be/Gya7ks8ZtVk

**Comment by Enclave2020** [comment]
https://youtu.be/PscXGpsF3dY

**Comment by Enclave2020** [comment]
https://youtu.be/H5NqIsnyTG8

**Comment by Enclave2020** [comment]
https://youtu.be/202fjZZO-tI

**Comment by Enclave2020** [comment]
https://youtu.be/dw0cvFJeu7Y

**Comment by Enclave2020** [comment]
https://youtu.be/3Ip1irYWXck

**Comment by Enclave2020** [comment]
https://youtu.be/e5O90uzvUA4

**Comment by Enclave2020** [comment]
https://youtu.be/RYPWxymohWs

**Comment by Enclave2020** [comment]
https://youtu.be/Rl6fyhZ0G5E

**Comment by Enclave2020** [comment]
https://youtu.be/73Bnu7S4X6M

**Comment by Enclave2020** [comment]
https://youtu.be/Alh6iIvVN9o

**Comment by Enclave2020** [comment]
https://youtu.be/TM2m371xLxw

**Comment by Enclave2020** [comment]
https://youtu.be/PJk3lJ-4m1M

**Comment by Enclave2020** [comment]
https://youtu.be/8u-Z9H9d7pw

**Comment by Enclave2020** [comment]
https://youtu.be/Gzfgjhqomoc
Пока что хватит, потом может еще добавлю)0

**Comment by Antoxer** [comment]
https://www.youtube.com/watch?v=696kM_7gu7Y
Ну що можна сказати?
Спасибі містер Дудец﻿

**Comment by Antoxer** [comment]
https://www.youtube.com/watch?v=y6120QOlsfU
DUDUDUDUDU

**Comment by Antoxer** [comment]
https://www.youtube.com/watch?v=ymNFyxvIdaM
Ностальгируем

**Comment by Antoxer** [comment]
https://www.youtube.com/watch?v=06CPuM0UVVM

**Comment by Antoxer** [comment]
https://www.youtube.com/watch?v=k85mRPqvMbE

**Comment by Strranger08** [comment]
ВЕРНИ ТО ЧТО Я ДОБАВЛЯЛ

**Comment by Antoxer** [comment]
https://www.youtube.com/watch?v=u3ltZmI5LQw

**Comment by Antoxer** [comment]
https://www.youtube.com/watch?v=YVkUvmDQ3HY
