### ISSUE TITLE
Износ брони

### ISSUE THREAD

**Issue by Enclave2020** [SomeOneUnknown/SATGv2#94]
Так как мы почти не умираем, а если и умираем то забираем свои вещи, то думаю стоит ввести износ брони, например, 50 попаданий и броня испорчена.
Или же, поднять цены на броню сильно
Еще вариант - удаление трупа игрока через 10 минут после смерти, чтобы нужно было спешить

**Comment by Strranger08** [comment]
я за 100 попаданий

**Comment by Antoxer** [comment]
Solidaren s Dimoy

**Comment by Enclave2020** [comment]
Решил что фича не нужна
