### ISSUE TITLE
Радио 2.0

### ISSUE THREAD

**Issue by Enclave2020** [SomeOneUnknown/SATGv2#95]
Из за забагованности старого радио, я полностью переписал его. Что нового?
- Радио теперь аддон. Вес карты упал с 11 метров до 100 кб.
- Добавлена поддержка нескольких станций.
- Управление хоткеями, отображение станции слева снизу.

В связи с этим, предлагаю каждому создать свою станцию (вплоть до 25 треков), у которой будет собственно название. AntoxaFM, Anime4Noobs и прочее.

Как добавить свою станцию:
1. Собираете всю музыку в одной папке
2. Спрашиваете нумерацию у меня, например 200. Переназываете по очереди треки в 200, 201, 202, 203..250
3. В текстовом файле по очереди записываете продолжительность трека в секундах. 1 = 120, 2 = 90
4. Пакуете архивом и кидаете мне

**Comment by Felk1n** [comment]
слишком сложно

**Comment by Felk1n** [comment]
просто запили чтоб можно было переключить трэк и всё

**Comment by Enclave2020** [comment]
@Felk1n Не, куча радиостанций с вашей любимой музыкой, аля ШТА 5, я уже сделал систему, осталось вам музыку свою поскидывать и название ваших радиостанций

**Comment by SadSapDept** [comment]
Новости Арматики,с вами Си130,,,, а еще запилить диктора что пагоду на след день будет рассказывать

**Comment by Enclave2020** [comment]
@SadSapDept СИИИИИИИСТОООООООТРИИДЦААААТЬ

**Comment by Strranger08** [comment]
ТЕХНОЛОГИИ

**Comment by Enclave2020** [comment]
Ну кароч вы поняли)0
