### ISSUE TITLE
Торговец еврей

### ISSUE THREAD

**Issue by Enclave2020** [SomeOneUnknown/SATGv2#96]
Egor 12:20 am
  кароче
  петровичу нужно платную услугу впилить
  по мотанию времени
  типо ПОСИДЕТЬ ПОПИТЬ ЧАЮ
Andrey 12:20 am
  ПОПИТЬ ЧАЮ ЗА СВОЙ СЧЕТ
Egor 2:20 am
  у всех черный экран
  вставляешь свои шутки
  и меняется время
  петрович еврей

**Comment by SadSapDept** [comment]
хм, может запилить тип задание что ему нужно привезти груз и он только потом откроет магазин?

**Comment by Enclave2020** [comment]
@SadSapDept Поздно, мы его уже нашли)0
Нужно ему квест со спаиванием, как у Кардана)0)0
